### ISSUE TITLE
run command "rake db:schema:load --trace" failed

### ISSUE THREAD

**Issue by Helenbj** [GeekPark/gpk_admin#26]
Based on the README.md in root directory of geekpark, I can create database successfully: 
```
helen@helen-Lenovo-Product:~/Documents/fbcodex/geekpark$ **rake db:create**
Created database 'geekpark_dev'
Created database 'geekpark_test'
```

while I cannot migrate data into database using the second command.
```
helen@helen-Lenovo-Product:~/Documents/fbcodex/geekpark$ **rake db:schema:load --trace**
** Invoke db:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
TypeError: no implicit conversion of nil into String
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:264:in `quote'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:264:in `block in origins'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:258:in `collect'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:258:in `origins'
/home/helen/Documents/fbcodex/geekpark/config/initializers/cors.rb:4:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:45:in `instance_eval'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:45:in `allow'
/home/helen/Documents/fbcodex/geekpark/config/initializers/cors.rb:3:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:30:in `instance_eval'
/var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:30:in `initialize'
/var/lib/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/stack.rb:35:in `new'
/var/lib/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/stack.rb:35:in `build'
/var/lib/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/stack.rb:100:in `block in build'
/var/lib/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/stack.rb:100:in `each'
/var/lib/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/stack.rb:100:in `inject'
/var/lib/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/stack.rb:100:in `build'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:508:in `block in app'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:504:in `synchronize'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:504:in `app'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
/home/helen/Documents/fbcodex/geekpark/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `each'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:schema:load => environment

```

As you can see, the key error is:

>  TypeError: no implicit conversion of nil into String

Ruby version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
PostgreSQL version: psql (PostgreSQL) 9.5.12

Can you tell me how to solve this problem, @dofy @shouya @flypiggy @chen7897499 @singt7  looking forward to your reply & best regards.

**Comment by playmyswift** [comment]
```
git clone https://github.com/GeekPark/geekpark.git --depth=1
cd geekpark
# install
bundle
# db
bundle exec rake db:create db:migrate
# cp config/app.yaml
cp config/app.yml.example config/app.yml
# mock data
bundle exec rails c
FactoryGirl.create_list(:column, 50)
FactoryGirl.create_list(:tag, 50)
FactoryGirl.create_list(:topic, 50)
FactoryGirl.create_list(:post, 50)
FactoryGirl.create_list(:comment, 50)
FactoryGirl.create_list(:ad, 50)
# start
bundle exec rails s -p 5000
```

**Comment by Helenbj** [comment]
Thanks for your reply, I'll also get error "**TypeError: no implicit conversion of nil into String**" when following above command "**bundle exec rake db:create db:migrate**". 
Finally I solve the problem by adding **to_s** method to translate nil to string explicitly in line 264 quote 
 /var/lib/gems/2.3.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:
```
250       class Resources
251         def initialize
252           @origins = []
253           @resources = []
254           @public_resources = false
255         end
256 
257         def origins(*args, &blk)
258           @origins = args.flatten.collect do |n|
259             case n
260             when Regexp,
261                  /^https?:\/\//,
262                  'file://'        then n
263             when '*'              then @public_resources = true; n
264             else                  Regexp.compile("^[a-z][a-z0-9.+-]*:\\\/\\\/#{Regexp.quote(n.to_s)}$")
265             end
266           end.flatten
267           @ori
```

After modify, there is no error report about "TypeError: no implicit conversion of nil into String".
